# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: 
      - 'main'
      - 'feature/**'
      - 'releases/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish -c Release -o out

    - name: check files
      run: |
        cd out 
        pwd
        ls -la

    - name: Docker Build and push
      env:
        image_tag: ${{ github.run_number }}
      run: |
        pwd
        ls -la
        docker buildx build -t freedomha/dotnetcoreexample:$image_tag --push .
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
